title: Ridho Perdana's Work
email: ridhoperdana@ymail.com
description: >- # this means to ignore newlines until "baseurl:"
  A little showcase of my work(s)
baseurl: "" # the subpath of your site, e.g. /blog
url: http://ridho.work # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cync48
github_username:  ridhoperdana

# Build settings
#theme: minima
remote_theme: YoussefRaafatNasry/portfolYOU
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
